disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - force_cast
  - colon
  - cyclomatic_complexity
  - unused_closure_parameter
  - for_where
  - unused_optional_binding


excluded:
  - Pods

identifier_name:
  min_length: 1
  max_length: 
    warning: 90
    error: 1000

line_length: 
  warning: 210 
  error: 350
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 600
  error: 1200