IdPathParameter:
  name: id
  in: path
  description: "id"
  required: true
  schema:
    type: integer
    format: int64
AuthorizationHeaderParameter:
  name: authorization
  in: header
  description: "value should be bearer: #{token_id}"
  required: true
  schema:
    type: string
UserIdUrlParameter:
  name: user_id
  in: query
  schema:
    type: integer
  description: Id of user
TrainerIdUrlParameter:
  name: trainer_id
  in: query
  schema:
    type: integer
  description: Id of trainer
